language: c
os:
  - linux
  - osx
sudo: required
dist: trusty
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis/install-debian.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./.travis/install-macos.sh; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis/build-debian.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./.travis/build-macos.sh; fi
deploy:
  - provider: releases
    api_key:
      secure: DA3tW0My37vbi2t3dZ061281Xm8KSIkeLdFZsQISrut0g1kkbWuBTPxAfvE3B6OE8p47wAclE/wxA1+obMTVkY0oYpd5u+JelYNHxU/oL8Ww0xdUANwKNJ1JD2EZP8nSz7JSvxuGILC6AFPoTjawsG97SXwiTyp7z0PA6nvzraE=
    skip_cleanup: true
    file_glob: true
    file:
      - ../*.deb
    on:
      repo: whitequark/solvespace
      tags: true
      condition: "$TRAVIS_OS_NAME == linux"
  - provider: releases
    api_key:
      secure: DA3tW0My37vbi2t3dZ061281Xm8KSIkeLdFZsQISrut0g1kkbWuBTPxAfvE3B6OE8p47wAclE/wxA1+obMTVkY0oYpd5u+JelYNHxU/oL8Ww0xdUANwKNJ1JD2EZP8nSz7JSvxuGILC6AFPoTjawsG97SXwiTyp7z0PA6nvzraE=
    skip_cleanup: true
    file: build/solvespace.dmg
    on:
      repo: whitequark/solvespace
      tags: true
      condition: "$TRAVIS_OS_NAME == osx"

