version: 2.1.{build}
clone_depth: 1
before_build:
  - git submodule update --init
  - mkdir build
  - cd build
  - set tag=x%APPVEYOR_REPO_TAG_NAME%
  - if %tag:~,9% == xrelease- (set BUILD_TYPE=RelWithDebInfo) else (set BUILD_TYPE=Debug)
  - cmake -G"Visual Studio 12" -T v120_xp -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..
build_script:
  - msbuild "C:\projects\solvespace\build\src\solvespace.vcxproj" /verbosity:minimal /property:Configuration=%BUILD_TYPE% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
  - path: build\src\Debug\solvespace.exe
    name: solvespace.exe
  - path: build\src\Debug\solvespace.pdb
    name: solvespace.pdb
  - path: build\src\RelWithDebInfo\solvespace.exe
    name: solvespace.exe
  - path: build\src\RelWithDebInfo\solvespace.pdb
    name: solvespace.pdb
deploy:
  - provider: GitHub
    auth_token:
      secure: Flqxu1cz6PyxVT1wzTP4bSrQOY8wFrO7pJxYxvjEkLqIUU4dsDQrs2rac/A9deet
    description: ""
    artifact: solvespace.exe
    on:
      appveyor_repo_tag: true
